DEFAULT_VERSION_SELECTION_STRATEGY = "continuity"
VERSION_SELECTION_CONTINUITY = "continuity"
VERSION_SELECTION_LATEST = "latest"
VERSION_SELECTION_STRATEGIES = (VERSION_SELECTION_CONTINUITY, VERSION_SELECTION_LATEST)

INITIALIZE_METHOD_NAME = "__initialize__"
WRAPPER_SELF_ARG_NAME = "_wrapper_self"
SWITCH_COUNT_ATTR_NAME = "_switch_count"

TEMPLATE_CURRENT_STATE_ATTR = "_CURRENT_STATE_PLACEHOLDER"
TEMPLATE_VERSION_SINGLETON_ATTR = "_VERSION_INSTANCES_SINGLETON_PLACEHOLDER"
TEMPLATE_SWITCH_TO_VERSION_FUNC = "_SWITCH_TO_VERSION_PLACEHOLDER"
TEMPLATE_SYNC_CALL_PLACEHOLDER = "_SYNC_CALL_PLACEHOLDER_"

# Project structure keys
PROJECT_SYNC_MODULES_KEY = "sync_modules"
PROJECT_INCOMPATIBILITIES_KEY = "incompatibilities"
PROJECT_NORMAL_FILES_KEY = "normal_files"
PROJECT_VERSIONED_MODULES_KEY = "versioned_modules"
PROJECT_MODULE_MAPPINGS_KEY = "module_mappings"
