DEFAULT_VERSION_SELECTION_STRATEGY = "continuity"
VERSION_SELECTION_CONTINUITY = "continuity"
VERSION_SELECTION_LATEST = "latest"
VERSION_SELECTION_STRATEGIES = (VERSION_SELECTION_CONTINUITY, VERSION_SELECTION_LATEST)

INITIALIZE_METHOD_NAME = "__initialize__"
WRAPPER_SELF_ARG_NAME = "_wrapper_self"
SWITCH_COUNT_ATTR_NAME = "_switch_count"

TEMPLATE_CURRENT_STATE_ATTR = "_CURRENT_STATE_PLACEHOLDER"
TEMPLATE_VERSION_SINGLETON_ATTR = "_VERSION_INSTANCES_SINGLETON_PLACEHOLDER"
TEMPLATE_SWITCH_TO_VERSION_FUNC = "_SWITCH_TO_VERSION_PLACEHOLDER"
TEMPLATE_SYNC_CALL_PLACEHOLDER = "_SYNC_CALL_PLACEHOLDER_"
